apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vb3lt8ffe-nodejs
  janus-idp.io/tekton: vb3lt8ffe-nodejs
  backstage.io/kubernetes-id: vb3lt8ffe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vb3lt8ffe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
