apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vb3lt8ffe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vb3lt8ffe-nodejs 
  name: vb3lt8ffe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: vb3lt8ffe-nodejs 
